### ISSUE TITLE
Error when starting neoss: no such user

### ISSUE THREAD

**Issue by linuxissuper** [PabloLec/neoss#186]
I'm trying to add neoss to nixpkgs and already built it with nix  
but when I'm starting it, it exits with an error:   
  
```
id: ‘100’: no such user
id: ‘100’: no such user
id: ‘100’: no such user
id: ‘100’: no such user
id: ‘100’: no such user
id: ‘100’: no such user
id: ‘100’: no such user
id: ‘100’: no such user
id: ‘100’: no such user
id: ‘100’: no such user
id: ‘100’: no such user
id: ‘100’: no such user
id: ‘100’: no such user
id: ‘100’: no such user
id: ‘100’: no such user
id: ‘100’: no such user
id: ‘100’: no such user
id: ‘100’: no such user
id: ‘100’: no such user
id: ‘100’: no such user
id: ‘100’: no such user
id: ‘100’: no such user
id: ‘100’: no such user
id: ‘100’: no such user
id: ‘100’: no such user
id: ‘100’: no such user
id: ‘100’: no such user
id: ‘100’: no such user
id: ‘100’: no such user
id: ‘100’: no such user
id: ‘100’: no such user
id: ‘100’: no such user
id: ‘100’: no such user
Error: Command failed: id -nu 100
id: ‘100’: no such user

    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at /nix/store/76lm8r14qxk3r93wwj50jym69l06dvxq-neoss-1.1.10/lib/node_modules/neoss/build/utils/users.js:83:50
    at Generator.next (<anonymous>)
    at /nix/store/76lm8r14qxk3r93wwj50jym69l06dvxq-neoss-1.1.10/lib/node_modules/neoss/build/utils/users.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/nix/store/76lm8r14qxk3r93wwj50jym69l06dvxq-neoss-1.1.10/lib/node_modules/neoss/build/utils/users.js:4:12)
    at getUserData (/nix/store/76lm8r14qxk3r93wwj50jym69l06dvxq-neoss-1.1.10/lib/node_modules/neoss/build/utils/users.js:72:12)
    at /nix/store/76lm8r14qxk3r93wwj50jym69l06dvxq-neoss-1.1.10/lib/node_modules/neoss/build/utils/getStats.js:53:58

```

**Comment by celevra** [comment]
same here
